language: node_js
sudo: false
node_js:
  - "8"
addons:
  apt:
    packages:
      - xvfb
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn
